name: ci it.bz.beacon.admin

on:
  push:
    branches: [ master, development ]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [ master, development ]
    paths-ignore:
      - "README.md"
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [12.x] # other node versions: 13.x, 14.x
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run test:unit
