name: CI

on: push


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          cache: 'npm'
      - name: install
        run: npm install
      - name: test
        run: npm run test:unit    
